### ISSUE TITLE
List of countries for location question

### ISSUE THREAD

**Issue by brownsarahm** [drnikki/open-demographics#4]
I don't know where such a list would be, but including an agreeable list or link to one here would be helpful. I've seen problems where the dropdown didn't include countries.

**Comment by drnikko** [comment]
@brownsarahm yes, agreed.  

This "list of countries" is inherently political because countries are, in many cases, occupied or results of colonial occupation.  I'm not sure what a good "authority" on a list of countries would be, and how to include/acknowledge dependent states and disputed areas.    It would be great if someone could find a source on a good way to handle this that's inclusive and accessible to folks who may not think about borders or politics.  

We will also (eventually) want to make a recommendation for ordering and display language.

**Comment by brownsarahm** [comment]
I did a bit of looking around, maybe ISO_3166-1 is a decent starting point? It's based on UN info & includes entries for territories and at least many major disputed areas.  

Also, there's this list of those countries with ISO codes available in many languages: https://github.com/umpirsky/country-list

**Comment by drnikko** [comment]
Thanks, @brownsarahm!  ISO_3166-1 makes a lot of sense and I think using https://github.com/umpirsky/country-list/blob/master/data/en/country.txt as a starting point is as good and as "neutral" as we will get for now. 

Do you feel comfortable adding a link to that (and your name to the contributors file if you would like) to the country question?

**Comment by drnikko** [comment]
Thank you!! <3
