### ISSUE TITLE
Intent to Fork the Repo into CHAOSS

### ISSUE THREAD

**Issue by germonprez** [drnikki/open-demographics#65]
Hi @drnikki 

In today's (August 19, 2020) CHAOSS Diversity & Inclusion call we discussed how to help maintain the excellent work that is in this repository. Based on our discussion, we plan on forking the open-demographics repository into the CHAOSS organization. We are certainly not looking to create any problems or confusion. Please let us know if you have questions or concerns. 

Again, thanks for the amazing work. We rely on this work in the CHAOSS project and firmly believe that it has a positive impact for all.

**Comment by drnikko** [comment]
Hi @germonprez!  Thanks for letting me know.  Open source repos are designed to be forked, though I'm not in love with the idea of your organization doing something like "taking it over" or "helping to maintain" via a forking process.  Is there a way that you can direct your efforts here if I give someone from your team admin capabilities?  I'm hesitant not because I don't need the help maintaining (I do!) but because I'd like to keep the project independent of control by open source orgs (which is also why this project isn't maintained by Drupal).  

Thoughts?

**Comment by germonprez** [comment]
Thanks for the response @drnikki 

This is a great solution! This work has greatly informed the ways that think about metrics in the CHAOSS project and we'd love to help in any way that advances this important work and maintains the original intentions of the founders :)

**Comment by GeorgLink** [comment]
Thanks @drnikki, 

100% agree that it would be better to continue the efforts here.

I'd be happy to help with the maintenance and facilitate engagement here.

**Comment by drnikko** [comment]
Ah, @germonprez, @GeorgLink - thank you for this quick and generous response!!   I'm happy to give each of you merge capabilities (or another if you let me know) so that we can work together on this.  

I'm _really_ happy to have help thinking about all of this and working to make it better and more inclusive (especially with our huge gaps in all non-North American concerns) and CHAOSS has been doing great work.

**Comment by GeorgLink** [comment]
Awesome! It would be great to sync up and outline how we want to move this project forward. Maybe schedule a call?

**Comment by germonprez** [comment]
That's a good idea (a call). I'd love to know your history and hopes for the project :)

**Comment by drnikko** [comment]
Hi! A call sounds great - we can do scheduling details via email if its easier (nikkilstevens at gmail), but I'm in Eastern Time and the first week of September is currently pretty open.

**Comment by GeorgLink** [comment]
+1

**Comment by drnikko** [comment]
Going to close this issue since we've got @germonprez and @GeorgLink on as maintainers and a plan to clean up the repo and get things ready for hacktoberfest.

**Comment by drnikko** [comment]
(close this issue with great thanks and excitement to have the CHAOSS team on board!)
